apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: flask_k8s_image
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31767

#After deploying you can force an external IP to be provisioned by using the following command (one line):

# kubectl patch svc flask-app-service -n default 
# -p '{"spec": {"type": "LoadBalancer", "externalIPs":["192.168.49.2"]}}'

#Change the IP itself if you want to.